### ISSUE TITLE
host your images on amazon S3. it's easy. :)

### ISSUE THREAD

**Issue by davidrunger** [DanielLacis/launchassist#7]
You might have noticed that they load insanely slowly from Heroku when not cached... :) Amazon is so much faster.

**Comment by DanielLacis** [comment]
I have it set up for a personal project, will probably hook it up on Sunday.  The images do take forever right now, will be hosting on S3 in various sizes or using Cloudinary.

**Comment by davidrunger** [comment]
:+1:
